version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: commute-db
    environment:
      POSTGRES_DB: knkommute
      POSTGRES_USER: kommute
      POSTGRES_PASSWORD: KuehneNagel
    volumes:
      - commute_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U commute_user -d shared_commute"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  commute_pg_data:
